# A Maternal Variant Foundation Model
#### Student Name: Emily Jagiello
#### Student ID: s4216579

Environment: Python 3 and Jupyter notebook

## Introduction
Combining:
- a DNA foundation model portion 
- a RNA portion using a BIRNA-BERT recommender system

## Importing libraries

In [1]:
import pandas as pd
import numpy as np
from Bio import SeqIO
from pathlib import Path
import pandas as pd
import gzip
from itertools import islice
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
import evaluate
import importlib

# Birna-BERT requirements
import torch
import transformers
from transformers import AutoModelForMaskedLM, AutoTokenizer, DataCollatorWithPadding, Trainer, TrainingArguments

Setting up BIRNA bert dependencies

In [2]:
import os

os.environ["HF_HUB_DISABLE_XET"] = "1"

from huggingface_hub import constants

print("Xet disabled:", constants.HF_HUB_DISABLE_XET)

Xet disabled: False

In [3]:
from huggingface_hub import login
login()

# Token: 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

## Loading data
Dataset used: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE120480

In [4]:
from Bio import SeqIO

f = r"b:\Emily_Analysis\fastq\SRR7903122_1.fastq"

with open(f) as handle:
    for i, record in enumerate(SeqIO.parse(handle, "fastq")):
        print(record.id)
        print(str(record.seq))
        print("length:", len(record.seq))
        print()

        if i == 4:
            break

SRR7903122.1
ATACCCTCTCCCCCGGATTTTCAAGGGCCAGCGAGAGCTCACCGGACGCCGCCGGAACCGCGACGCTTTCCAAGGCACGGGCCCCTCTCTCGGGGCGAACC
length: 101

SRR7903122.2
AGCCAAGCAAGAAGCAGAAGATACATCTCTTACGTGGGTATCTGCGCCCAATAGATGACACTTTCCTGCAGTGAGGACAACGTGCCAAAGTGCGGTCTGTG
length: 101

SRR7903122.3
TGGATTTCTGTTGCGTTTCCTCCATGTTGGAGGGTGTCGGAATAGAGTCTGAGAAGCAGAAGGAGGTCTGGGAGTCATGCAGGAATGAATACTTCTGGTCC
length: 101

SRR7903122.4
NTCGTTCTTGATTCGCTGGATAGCCTGGCTTGTGTCATCCACAGACCGCTGCAGATTCGTGATGAGGTTCCTCTGCTGCACCTGGGTCAGGTTCAGGTTGT
length: 101

SRR7903122.5
GTCGCGTTACCGCACTGGACGCCTCGCGGCGCCCATCTCCGCCACTCCGGATTCGGGGATCTGAACCCGACTCCCTTTCGATCGGCCGAGGGCAACGGAGG
length: 101

In [5]:
# Main directory
folder = Path(r"B:\Emily_Analysis\unzipped")
vcf_folder = Path(r"B:\Emily_Analysis\vcf")
fastq_folder = Path(r"B:\Emily_Analysis\fastq")
# Test Print
# directory for test print
zipped = Path(r"B:\Emily_Analysis")
test_file = zipped / "GSM3401375_ETB.cons.fasta.gz"

with gzip.open(test_file, 'rt') as value:
    records = list(islice(SeqIO.parse(value, 'fasta'), 2))

for record in records:
    print(record)

ID: chr1
Name: chr1
Description: chr1 1
Number of features: 0
Seq('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...NNN')
ID: chr2
Name: chr2
Description: chr2 2
Number of features: 0
Seq('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...NNN')

In [6]:
groups = {
     # ETB
        "SRR7903122": "caesarean section elective term delivery (ETB)",
        "SRR7903123": "caesarean section elective term delivery (ETB)",
        "SRR7903124": "caesarean section elective term delivery (ETB)",
        "SRR7903125": "caesarean section elective term delivery (ETB)",
        "SRR7903126": "caesarean section elective term delivery (ETB)",
        "SRR7903127": "caesarean section elective term delivery (ETB)",
    
        # SPTB
        "SRR7903128": "spontaneous preterm birth (SPTB)",
        "SRR7903129": "spontaneous preterm birth (SPTB)",
        "SRR7903130": "spontaneous preterm birth (SPTB)",
        "SRR7903131": "spontaneous preterm birth (SPTB)",
        "SRR7903132": "spontaneous preterm birth (SPTB)",
        "SRR7903133": "spontaneous preterm birth (SPTB)",
    
        # STB
        "SRR7903134": "spontaneous term birth (STB)",
        "SRR7903135": "spontaneous term birth (STB)",
        "SRR7903136": "spontaneous term birth (STB)",
        "SRR7903137": "spontaneous term birth (STB)",
        "SRR7903138": "spontaneous term birth (STB)",
        "SRR7903139": "spontaneous term birth (STB)",
}

patients = []

for group, record in groups.items():
    if record in {"spontaneous preterm birth (SPTB)"}:
        phenotype = 1
    else:
        phenotype = 0

    patients.append(
            {
                "sample": group,
                "record": record,
                "fastq_1": fastq_folder / f"{group}_1.fastq",
                "fastq_2": fastq_folder / f"{group}_2.fastq",
                "phenotype": phenotype,
            }
        )

In [7]:
# cDNA Fasta Version
"""# Inspecting our Sequences in PTB dataset
patients = []

for vcf_file in sorted(vcf_folder.glob("*.vcf.gz")):
    sample_name = vcf_file.name.removesuffix(".vcf.gz")
    fasta_file = folder / f"{sample_name}.cons.fasta"
    if sample_name == "SPTB" or sample_name == "ETB":
        phenotype = 1
    else:
        phenotype = 0

    fasta_file = folder / f"{sample_name}.cons.fasta"

    # Finding the associated fasta file for the vcf file


    patients.append(
        {
            "sample": sample_name,
            "vcf_file": vcf_file,
            "fasta_file": fasta_file,
            "phenotype": phenotype,
        }
    )

patients[0:2]"""

'# Inspecting our Sequences in PTB dataset\npatients = []\n\nfor vcf_file in sorted(vcf_folder.glob("*.vcf.gz")):\n    sample_name = vcf_file.name.removesuffix(".vcf.gz")\n    fasta_file = folder / f"{sample_name}.cons.fasta"\n    if sample_name == "SPTB" or sample_name == "ETB":\n        phenotype = 1\n    else:\n        phenotype = 0\n\n    fasta_file = folder / f"{sample_name}.cons.fasta"\n\n    # Finding the associated fasta file for the vcf file\n\n\n    patients.append(\n        {\n            "sample": sample_name,\n            "vcf_file": vcf_file,\n            "fasta_file": fasta_file,\n            "phenotype": phenotype,\n        }\n    )\n\npatients[0:2]'

In [8]:
'''# Might change for the biosequence one!! 
# https://biopython.org/docs/latest/Tutorial/chapter_quick_start.html 
def read_fasta(fasta):
    sequence =[]
    with open(fasta, 'r') as file:
        for line in file:
            line = line.strip()
            if line.startswith('>'):
                continue
            sequence.append(line)
    return "".join(sequence)'''

'# Might change for the biosequence one!! \n# https://biopython.org/docs/latest/Tutorial/chapter_quick_start.html \ndef read_fasta(fasta):\n    sequence =[]\n    with open(fasta, \'r\') as file:\n        for line in file:\n            line = line.strip()\n            if line.startswith(\'>\'):\n                continue\n            sequence.append(line)\n    return "".join(sequence)'

Using that to create a patient dataset

In [9]:
PTB_examine = pd.DataFrame(patients)
PTB_examine.head()

,sample,record,fastq_1,fastq_2,phenotype
0,SRR7903122,caesarean section elective term delivery (ETB),B:\Emily_Analysis\fastq\SRR7903122_1.fastq,B:\Emily_Analysis\fastq\SRR7903122_2.fastq,0
1,SRR7903123,caesarean section elective term delivery (ETB),B:\Emily_Analysis\fastq\SRR7903123_1.fastq,B:\Emily_Analysis\fastq\SRR7903123_2.fastq,0
2,SRR7903124,caesarean section elective term delivery (ETB),B:\Emily_Analysis\fastq\SRR7903124_1.fastq,B:\Emily_Analysis\fastq\SRR7903124_2.fastq,0
3,SRR7903125,caesarean section elective term delivery (ETB),B:\Emily_Analysis\fastq\SRR7903125_1.fastq,B:\Emily_Analysis\fastq\SRR7903125_2.fastq,0
4,SRR7903126,caesarean section elective term delivery (ETB),B:\Emily_Analysis\fastq\SRR7903126_1.fastq,B:\Emily_Analysis\fastq\SRR7903126_2.fastq,0

# Task 1. Base Birna-BERT sequence recommender model
Provides a base from which fine tuning improvements and such can be implemented

### Creating a simple patient class to allow for batch loading by patient

BiRNA-BERT setup

In [10]:
# Adjusted from Documentation (https://huggingface.co/buetnlpbio/birna-bert)

tokenizer = AutoTokenizer.from_pretrained("buetnlpbio/birna-tokenizer")
config=transformers.BertConfig.from_pretrained("EmilyJagiello/birna-bert")

pretrained_birnabert = AutoModelForMaskedLM.from_pretrained("EmilyJagiello/birna-bert",config=config,trust_remote_code=True, low_cpu_mem_usage=False)


# defining class labels
id2label = {0: "NEGATIVE", 1: "POSITIVE"}
label2id = {"NEGATIVE":0, "POSITIVE":1}

config.num_labels = 2
config.id2label = id2label
config.label2id = label2id
config.problem_type = 'single_label_classification'

# To get sequence embeddings 
seq_embed = pretrained_birnabert(**tokenizer("AGCTACGTACGT", return_tensors="pt"))
print(seq_embed.logits.shape)

# To get nucleotide embeddings 
char_embed = pretrained_birnabert(**tokenizer("A G C T A C G T A C G T", return_tensors='pt'))
print(char_embed.logits.shape)

#mysterybert = mysterybert.to("device")

C:\Users\Michael\.cache\huggingface\modules\transformers_modules\EmilyJagiello\birna_hyphen_bert\1b9497c565e625ffce0a922cb66386dff0f30917\bert_layers.py:174: UserWarning: Unable to import Triton; defaulting MosaicBERT attention implementation to pytorch (this will reduce throughput when using this model).
  warnings.warn(

Loading weights:   0%|          | 0/142 [00:00<?, ?it/s]

[transformers] `use_return_dict` is deprecated! Use `return_dict` instead!

torch.Size([1, 6, 4096])
torch.Size([1, 14, 4096])

Then from BiRNA BERT's bert_layers.py file (https://huggingface.co/buetnlpbio/birna-bert/blob/main/bert_layers.py):
'Currently, Mosaic BERT is available for masked language modeling :class:`BertForMaskedLM` and sequence
classification :class:`BertForSequenceClassification`. We aim to expand this catalogue in future releases.'

In [11]:
birna_module = importlib.import_module(pretrained_birnabert.__class__.__module__)

BiRNABertForSequenceClassification = getattr(birna_module, "BertForSequenceClassification")

model = BiRNABertForSequenceClassification(config)

# Copying pretrained BiRNA-BERT weights
missing, unexpected = model.load_state_dict(pretrained_birnabert.state_dict(), strict = False)
print(missing)
print(unexpected)

['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'classifier.weight', 'classifier.bias']
['cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias']

##### Creating the training test split

In [12]:
train_patients, test_patients = train_test_split(patients, test_size = 0.2, random_state = 22, stratify=[patient["phenotype"]for patient in patients])
# Stratify to try and maintain phenotype distribution in both train and test split

In [13]:
reads_per_patient = 10000
def load_rna(patient, max_reads = None):
    loaded_sequences = []
    with open(patient["fastq_1"]) as file:
        sequences = SeqIO.parse(file, "fastq")
        for i, record in enumerate(sequences):
            if max_reads is None or i < max_reads:
                loaded_sequences.append({"sequence": str(record.seq), "labels": patient["phenotype"], "sample":patient["sample"]})
    return loaded_sequences

Loading RNA sequences

In [14]:
train_samples = []
test_samples = []
for patient in train_patients:
    print(f'Train: Loading {patient}')
    train_samples.extend(load_rna(patient, max_reads=reads_per_patient))

for patient in test_patients:
    print(f'Test: Loading {patient}')
    test_samples.extend(load_rna(patient, max_reads=reads_per_patient))

print(f'Number of train sequences are {len(train_samples)}, while the number of test sequences are {len(test_samples)}')

Train: Loading {'sample': 'SRR7903124', 'record': 'caesarean section elective term delivery (ETB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903124_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903124_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903135', 'record': 'spontaneous term birth (STB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903135_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903135_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903129', 'record': 'spontaneous preterm birth (SPTB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903129_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903129_2.fastq'), 'phenotype': 1}
Train: Loading {'sample': 'SRR7903123', 'record': 'caesarean section elective term delivery (ETB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903123_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903123_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903128', 'record': 'spontaneous preterm birth (SPTB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903128_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903128_2.fastq'), 'phenotype': 1}
Train: Loading {'sample': 'SRR7903136', 'record': 'spontaneous term birth (STB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903136_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903136_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903137', 'record': 'spontaneous term birth (STB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903137_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903137_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903125', 'record': 'caesarean section elective term delivery (ETB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903125_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903125_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903133', 'record': 'spontaneous preterm birth (SPTB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903133_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903133_2.fastq'), 'phenotype': 1}
Train: Loading {'sample': 'SRR7903138', 'record': 'spontaneous term birth (STB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903138_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903138_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903131', 'record': 'spontaneous preterm birth (SPTB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903131_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903131_2.fastq'), 'phenotype': 1}
Train: Loading {'sample': 'SRR7903139', 'record': 'spontaneous term birth (STB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903139_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903139_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903134', 'record': 'spontaneous term birth (STB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903134_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903134_2.fastq'), 'phenotype': 0}
Train: Loading {'sample': 'SRR7903132', 'record': 'spontaneous preterm birth (SPTB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903132_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903132_2.fastq'), 'phenotype': 1}
Test: Loading {'sample': 'SRR7903122', 'record': 'caesarean section elective term delivery (ETB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903122_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903122_2.fastq'), 'phenotype': 0}
Test: Loading {'sample': 'SRR7903130', 'record': 'spontaneous preterm birth (SPTB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903130_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903130_2.fastq'), 'phenotype': 1}
Test: Loading {'sample': 'SRR7903126', 'record': 'caesarean section elective term delivery (ETB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903126_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903126_2.fastq'), 'phenotype': 0}
Test: Loading {'sample': 'SRR7903127', 'record': 'caesarean section elective term delivery (ETB)', 'fastq_1': WindowsPath('B:/Emily_Analysis/fastq/SRR7903127_1.fastq'), 'fastq_2': WindowsPath('B:/Emily_Analysis/fastq/SRR7903127_2.fastq'), 'phenotype': 0}
Number of train sequences are 140000, while the number of test sequences are 40000

In [15]:
class RNASequenceClass(Dataset):
    def __init__(self, sequences):
        self.sequences = sequences
    def __len__(self):
        return len(self.sequences)
    def __getitem__(self, index):
        # loads specifically through this function
        sequence = self.sequences[index]
        tokenized = tokenizer(sequence["sequence"], truncation=True, max_length= 128)
        tokenized['labels'] = sequence['labels'] ## 
        return tokenized

PTB_train = RNASequenceClass(train_samples)
PTB_test = RNASequenceClass(test_samples)

In [16]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer) # Dynamic padding
# loader = DataLoader(PTB_fasta, batch_size=4, num_workers=4, collate_fn=data_collator)
# https://huggingface.co/docs/transformers/tasks/sequence_classification

##### Adding evaluation metrics

In [17]:
accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
f1 = evaluate.load("f1")
recall = evaluate.load("recall")
AUROC = evaluate.load("roc_auc")


def compute_metrics(eval_pred):
    logits, true_labels = eval_pred
    predicted_labels = np.argmax(logits, axis = 1)
    accuracy_result = accuracy.compute(predictions = predicted_labels, references=true_labels)
    precision_result = precision.compute(predictions = predicted_labels, references=true_labels)
    f1_result = f1.compute(predictions = predicted_labels, references=true_labels)
    recall_result = recall.compute(predictions = predicted_labels, references=true_labels)

    # For auroc calculate softmax to convert logits to class probabilities and then use probabilities from class 1
    # https://docs.pytorch.org/docs/2.14/generated/torch.nn.Softmax.html, https://academic.oup.com/imajna/article/41/4/2311/5893596?login=false (documentation on why its important)
    class_probabilities = torch.nn.functional.softmax(torch.tensor(logits), dim=-1).numpy() 
    positive_class_probabilities = class_probabilities[:, 1]

    AUROC_result = AUROC.compute(prediction_scores = positive_class_probabilities, references=true_labels)

    return {"accuracy": accuracy_result['accuracy'], "precision": precision_result['precision'], "f1": f1_result['f1'], "recall": recall_result['recall'], "AUROC": AUROC_result['roc_auc'],}

# https://huggingface.co/docs/transformers/tasks/sequence_classification

Downloading builder script: 0.00B [00:00, ?B/s]

### Training

In [ ]:
training_args = TrainingArguments(
    learning_rate = 2e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 32,
    num_train_epochs = 1,
    weight_decay = 0.01,
    eval_strategy = "epoch",
    save_strategy = "epoch",
    load_best_model_at_end = True,
    output_dir=r"B:\Emily_Analysis\Output",
    fp16=True,
    dataloader_num_workers = 0, # controls how many workers used to load Fastas (Patients)
    logging_steps=50,
    report_to = "none"
)

In [19]:
print("train patients:", len(train_patients))
print("test patients:", len(test_patients))

print("train_reads:", len(train_samples))
print("test_reads:", len(test_samples))

print("PTB_train:", len(PTB_train))
print("PTB_test:", len(PTB_test))

train patients: 14
test patients: 4
train_reads: 140000
test_reads: 40000
PTB_train: 140000
PTB_test: 40000

In [20]:
trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = PTB_train,
    eval_dataset = PTB_test,
    processing_class = tokenizer,
    data_collator = data_collator,
    compute_metrics = compute_metrics
)

trainer.train()

b:\Uni\envs\uni\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=8750, training_loss=0.6536726771763393, metrics={'train_runtime': 425.9841, 'train_samples_per_second': 328.651, 'train_steps_per_second': 20.541, 'total_flos': 2467119837668352.0, 'train_loss': 0.6536726771763393, 'epoch': 1.0})

Suspicious-metrics-indicating-the-dataset-is-unlikely-to-be-very-finetunable

## Task Name. What would we like to add?

Describe please c:

### Saving outputs
Save the count vector representation as per spectification.

## Summary
Give a short summary and anything you would like to talk about the assessment tasks here.

## References